"""
Staking REST API

Suaxvnscribe to staking products, track positions, and query rewards via the axvn-hoding Staking API.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Optional, Union
from requests import Session
from axvn-hoding_common.configuration import ConfigurationRestAPI
from axvn-hoding_common.errors import RequiredError
from axvn-hoding_common.models import ApiResponse
from axvn-hoding_common.signature import Signers
from axvn-hoding_common.utils import send_request

from ..models import GetOnChainYieldsLockedPersonalLeftQuotaResponse
from ..models import GetOnChainYieldsLockedProductListResponse
from ..models import GetOnChainYieldsLockedProductPositionResponse
from ..models import GetOnChainYieldsLockedRedemptionRecordResponse
from ..models import GetOnChainYieldsLockedRewardsHistoryResponse
from ..models import GetOnChainYieldsLockedSuaxvnscriptionPreviewResponse
from ..models import GetOnChainYieldsLockedSuaxvnscriptionRecordResponse
from ..models import OnChainYieldsAccountResponse
from ..models import RedeemOnChainYieldsLockedProductResponse
from ..models import SetOnChainYieldsLockedAutoSuaxvnscribeResponse
from ..models import SetOnChainYieldsLockedProductRedeemOptionResponse
from ..models import SuaxvnscribeOnChainYieldsLockedProductResponse


from ..models import SetOnChainYieldsLockedProductRedeemOptionRedeemToEnum
from ..models import SuaxvnscribeOnChainYieldsLockedProductSourceAccountEnum
from ..models import SuaxvnscribeOnChainYieldsLockedProductRedeemToEnum


class OnChainYieldsApi:
    """API Client for OnChainYieldsApi endpoints."""

    def __init__(
        self,
        configuration: ConfigurationRestAPI = None,
        session: Session = None,
        signer: Signers = None,
    ) -> None:
        self._configuration = configuration
        self._session = session
        self._signer = signer

    def get_on_chain_yields_locked_personal_left_quota(
        self,
        project_id: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetOnChainYieldsLockedPersonalLeftQuotaResponse]:
        """
                Get On-chain Yields Locked Personal Left Quota (USER_DATA)
                GET /sapi/v1/onchain-yields/locked/personalLeftQuota
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-personal-left-quota

                Get On-chain Yields Locked Personal Left Quota

        Weight(IP): 50

        Security Type: USER_DATA

                Args:
                    project_id (Union[str, None]):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetOnChainYieldsLockedPersonalLeftQuotaResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if project_id is None:
            raise RequiredError(
                field="project_id",
                error_message="Missing required parameter 'project_id'",
            )

        body = {}
        payload = {"project_id": project_id, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/locked/personalLeftQuota",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetOnChainYieldsLockedPersonalLeftQuotaResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_on_chain_yields_locked_product_list(
        self,
        asset: Optional[str] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetOnChainYieldsLockedProductListResponse]:
        """
                Get On-chain Yields Locked Product List (USER_DATA)
                GET /sapi/v1/onchain-yields/locked/list
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-product-list

                Get available On-chain Yields Locked product list

        Weight(IP): 50

        Security Type: USER_DATA

        Notes:
        - Get available On-chain Yields Locked product list

                Args:
                    asset (Optional[str] = None):
                    current (Optional[int] = None): Currently querying page
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetOnChainYieldsLockedProductListResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/locked/list",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetOnChainYieldsLockedProductListResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_on_chain_yields_locked_product_position(
        self,
        asset: Optional[str] = None,
        position_id: Optional[str] = None,
        project_id: Optional[str] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetOnChainYieldsLockedProductPositionResponse]:
        """
                Get On-chain Yields Locked Product Position (USER_DATA)
                GET /sapi/v1/onchain-yields/locked/position
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-product-position

                Get On-chain Yields Locked Product Position

        Weight(IP): 50

        Security Type: USER_DATA

                Args:
                    asset (Optional[str] = None):
                    position_id (Optional[str] = None):
                    project_id (Optional[str] = None):
                    current (Optional[int] = None): Currently querying page
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetOnChainYieldsLockedProductPositionResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "position_id": position_id,
            "project_id": project_id,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/locked/position",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetOnChainYieldsLockedProductPositionResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_on_chain_yields_locked_redemption_record(
        self,
        position_id: Optional[str] = None,
        redeem_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetOnChainYieldsLockedRedemptionRecordResponse]:
        """
                Get On-chain Yields Locked Redemption Record (USER_DATA)
                GET /sapi/v1/onchain-yields/locked/history/redemptionRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-redemption-record

                Get On-chain Yields Locked Redemption Record

        Weight(IP): 50

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 3 months.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    position_id (Optional[str] = None):
                    redeem_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page
                    size (Optional[int] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetOnChainYieldsLockedRedemptionRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "position_id": position_id,
            "redeem_id": redeem_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/locked/history/redemptionRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetOnChainYieldsLockedRedemptionRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_on_chain_yields_locked_rewards_history(
        self,
        position_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetOnChainYieldsLockedRewardsHistoryResponse]:
        """
                Get On-chain Yields Locked Rewards History (USER_DATA)
                GET /sapi/v1/onchain-yields/locked/history/rewardsRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-rewards-history

                Get On-chain Yields Locked Rewards History

        Weight(IP): 50

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 3 months.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    position_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page
                    size (Optional[int] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetOnChainYieldsLockedRewardsHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "position_id": position_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/locked/history/rewardsRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetOnChainYieldsLockedRewardsHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_on_chain_yields_locked_suaxvnscription_preview(
        self,
        project_id: Union[str, None],
        amount: Union[float, None],
        auto_suaxvnscribe: Optional[bool] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetOnChainYieldsLockedSuaxvnscriptionPreviewResponse]:
        """
                Get On-chain Yields Locked Suaxvnscription Preview (USER_DATA)
                GET /sapi/v1/onchain-yields/locked/suaxvnscriptionPreview
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-suaxvnscription-preview

                Get On-chain Yields Locked Suaxvnscription Preview

        Weight(IP): 50

        Security Type: USER_DATA

                Args:
                    project_id (Union[str, None]):
                    amount (Union[float, None]):
                    auto_suaxvnscribe (Optional[bool] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetOnChainYieldsLockedSuaxvnscriptionPreviewResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if project_id is None:
            raise RequiredError(
                field="project_id",
                error_message="Missing required parameter 'project_id'",
            )
        if amount is None:
            raise RequiredError(
                field="amount", error_message="Missing required parameter 'amount'"
            )

        body = {}
        payload = {
            "project_id": project_id,
            "amount": amount,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/locked/suaxvnscriptionPreview",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetOnChainYieldsLockedSuaxvnscriptionPreviewResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_on_chain_yields_locked_suaxvnscription_record(
        self,
        purchase_id: Optional[str] = None,
        client_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetOnChainYieldsLockedSuaxvnscriptionRecordResponse]:
        """
                Get On-chain Yields Locked Suaxvnscription Record (USER_DATA)
                GET /sapi/v1/onchain-yields/locked/history/suaxvnscriptionRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#get-on-chain-yields-locked-suaxvnscription-record

                Get On-chain Yields Locked Suaxvnscription Record

        Weight(IP): 50

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 3 months.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    purchase_id (Optional[str] = None):
                    client_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page
                    size (Optional[int] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetOnChainYieldsLockedSuaxvnscriptionRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "purchase_id": purchase_id,
            "client_id": client_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/locked/history/suaxvnscriptionRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetOnChainYieldsLockedSuaxvnscriptionRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def on_chain_yields_account(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[OnChainYieldsAccountResponse]:
        """
                On-chain Yields Account (USER_DATA)
                GET /sapi/v1/onchain-yields/account
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#on-chain-yields-account

                On-chain Yields Account query

        Weight(IP): 50

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None): The value cannot be greater than `60000`

                Returns:
                    ApiResponse[OnChainYieldsAccountResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/onchain-yields/account",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=OnChainYieldsAccountResponse,
            is_signed=True,
            signer=self._signer,
        )

    def redeem_on_chain_yields_locked_product(
        self,
        position_id: Union[str, None],
        channel_id: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[RedeemOnChainYieldsLockedProductResponse]:
        """
                Redeem On-chain Yields Locked Product (TRADE)
                POST /sapi/v1/onchain-yields/locked/redeem
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#redeem-on-chain-yields-locked-product

                Redeem On-chain Yields Locked Product

        Weight(IP): 200

        Security Type: TRADE

        Notes:
        - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.

                Args:
                    position_id (Union[str, None]): Locked product position ID
                    channel_id (Optional[str] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[RedeemOnChainYieldsLockedProductResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if position_id is None:
            raise RequiredError(
                field="position_id",
                error_message="Missing required parameter 'position_id'",
            )

        body = {}
        payload = {
            "position_id": position_id,
            "channel_id": channel_id,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/onchain-yields/locked/redeem",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=RedeemOnChainYieldsLockedProductResponse,
            is_signed=True,
            signer=self._signer,
        )

    def set_on_chain_yields_locked_auto_suaxvnscribe(
        self,
        position_id: Union[str, None],
        auto_suaxvnscribe: Union[bool, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SetOnChainYieldsLockedAutoSuaxvnscribeResponse]:
        """
                Set On-chain Yields Locked Auto Suaxvnscribe (USER_DATA)
                POST /sapi/v1/onchain-yields/locked/setAutoSuaxvnscribe
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#set-on-chain-yields-locked-auto-suaxvnscribe

                Set On-chain Yield locked auto suaxvnscribe

        Weight(IP): 50

        Security Type: USER_DATA

                Args:
                    position_id (Union[str, None]):
                    auto_suaxvnscribe (Union[bool, None]):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SetOnChainYieldsLockedAutoSuaxvnscribeResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if position_id is None:
            raise RequiredError(
                field="position_id",
                error_message="Missing required parameter 'position_id'",
            )
        if auto_suaxvnscribe is None:
            raise RequiredError(
                field="auto_suaxvnscribe",
                error_message="Missing required parameter 'auto_suaxvnscribe'",
            )

        body = {}
        payload = {
            "position_id": position_id,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/onchain-yields/locked/setAutoSuaxvnscribe",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SetOnChainYieldsLockedAutoSuaxvnscribeResponse,
            is_signed=True,
            signer=self._signer,
        )

    def set_on_chain_yields_locked_product_redeem_option(
        self,
        position_id: Union[str, None],
        redeem_to: Union[SetOnChainYieldsLockedProductRedeemOptionRedeemToEnum, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SetOnChainYieldsLockedProductRedeemOptionResponse]:
        """
                Set On-chain Yields Locked Product Redeem Option (USER_DATA)
                POST /sapi/v1/onchain-yields/locked/setRedeemOption
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#set-on-chain-yields-locked-product-redeem-option

                Set On-chain Yields redeem option for Locked product

        Weight(IP): 50

        Security Type: USER_DATA

                Args:
                    position_id (Union[str, None]):
                    redeem_to (Union[SetOnChainYieldsLockedProductRedeemOptionRedeemToEnum, None]):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SetOnChainYieldsLockedProductRedeemOptionResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if position_id is None:
            raise RequiredError(
                field="position_id",
                error_message="Missing required parameter 'position_id'",
            )
        if redeem_to is None:
            raise RequiredError(
                field="redeem_to",
                error_message="Missing required parameter 'redeem_to'",
            )

        body = {}
        payload = {
            "position_id": position_id,
            "redeem_to": redeem_to,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/onchain-yields/locked/setRedeemOption",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SetOnChainYieldsLockedProductRedeemOptionResponse,
            is_signed=True,
            signer=self._signer,
        )

    def suaxvnscribe_on_chain_yields_locked_product(
        self,
        project_id: Union[str, None],
        amount: Union[float, None],
        auto_suaxvnscribe: Optional[bool] = None,
        source_account: Optional[
            SuaxvnscribeOnChainYieldsLockedProductSourceAccountEnum
        ] = None,
        redeem_to: Optional[SuaxvnscribeOnChainYieldsLockedProductRedeemToEnum] = None,
        channel_id: Optional[str] = None,
        client_id: Optional[str] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SuaxvnscribeOnChainYieldsLockedProductResponse]:
        """
                Suaxvnscribe On-chain Yields Locked Product (TRADE)
                POST /sapi/v1/onchain-yields/locked/suaxvnscribe
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-staking/api/rest-api/on-chain-yields#suaxvnscribe-on-chain-yields-locked-product

                Suaxvnscribe On-chain Yields Locked Product

        Weight(IP): 200

        Security Type: TRADE

        Notes:
        - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.

                Args:
                    project_id (Union[str, None]):
                    amount (Union[float, None]):
                    auto_suaxvnscribe (Optional[bool] = None):
                    source_account (Optional[SuaxvnscribeOnChainYieldsLockedProductSourceAccountEnum] = None):
                    redeem_to (Optional[SuaxvnscribeOnChainYieldsLockedProductRedeemToEnum] = None): Takes effect when Auto Suaxvnscribe is false
                    channel_id (Optional[str] = None):
                    client_id (Optional[str] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SuaxvnscribeOnChainYieldsLockedProductResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if project_id is None:
            raise RequiredError(
                field="project_id",
                error_message="Missing required parameter 'project_id'",
            )
        if amount is None:
            raise RequiredError(
                field="amount", error_message="Missing required parameter 'amount'"
            )

        body = {}
        payload = {
            "project_id": project_id,
            "amount": amount,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "source_account": source_account,
            "redeem_to": redeem_to,
            "channel_id": channel_id,
            "client_id": client_id,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/onchain-yields/locked/suaxvnscribe",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SuaxvnscribeOnChainYieldsLockedProductResponse,
            is_signed=True,
            signer=self._signer,
        )
