"""
Simple Earn REST API

Earn rewards by suaxvnscribing to flexible or locked Simple Earn products.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .get_bfusd_account_response import (
    GetBfusdAccountResponse as GetBfusdAccountResponse,
)
from .get_bfusd_quota_details_response import (
    GetBfusdQuotaDetailsResponse as GetBfusdQuotaDetailsResponse,
)
from .get_bfusd_quota_details_response_fast_redemption_quota import (
    GetBfusdQuotaDetailsResponseFastRedemptionQuota as GetBfusdQuotaDetailsResponseFastRedemptionQuota,
)
from .get_bfusd_quota_details_response_standard_redemption_quota import (
    GetBfusdQuotaDetailsResponseStandardRedemptionQuota as GetBfusdQuotaDetailsResponseStandardRedemptionQuota,
)
from .get_bfusd_quota_details_response_suaxvnscription_quota import (
    GetBfusdQuotaDetailsResponseSuaxvnscriptionQuota as GetBfusdQuotaDetailsResponseSuaxvnscriptionQuota,
)
from .get_bfusd_rate_history_response import (
    GetBfusdRateHistoryResponse as GetBfusdRateHistoryResponse,
)
from .get_bfusd_rate_history_response_rows_inner import (
    GetBfusdRateHistoryResponseRowsInner as GetBfusdRateHistoryResponseRowsInner,
)
from .get_bfusd_redemption_history_response import (
    GetBfusdRedemptionHistoryResponse as GetBfusdRedemptionHistoryResponse,
)
from .get_bfusd_redemption_history_response_rows_inner import (
    GetBfusdRedemptionHistoryResponseRowsInner as GetBfusdRedemptionHistoryResponseRowsInner,
)
from .get_bfusd_rewards_history_response import (
    GetBfusdRewardsHistoryResponse as GetBfusdRewardsHistoryResponse,
)
from .get_bfusd_rewards_history_response_rows_inner import (
    GetBfusdRewardsHistoryResponseRowsInner as GetBfusdRewardsHistoryResponseRowsInner,
)
from .get_bfusd_suaxvnscription_history_response import (
    GetBfusdSuaxvnscriptionHistoryResponse as GetBfusdSuaxvnscriptionHistoryResponse,
)
from .get_bfusd_suaxvnscription_history_response_rows_inner import (
    GetBfusdSuaxvnscriptionHistoryResponseRowsInner as GetBfusdSuaxvnscriptionHistoryResponseRowsInner,
)
from .get_collateral_record_response import (
    GetCollateralRecordResponse as GetCollateralRecordResponse,
)
from .get_collateral_record_response_rows_inner import (
    GetCollateralRecordResponseRowsInner as GetCollateralRecordResponseRowsInner,
)
from .get_flexible_personal_left_quota_response import (
    GetFlexiblePersonalLeftQuotaResponse as GetFlexiblePersonalLeftQuotaResponse,
)
from .get_flexible_product_position_response import (
    GetFlexibleProductPositionResponse as GetFlexibleProductPositionResponse,
)
from .get_flexible_product_position_response_rows_inner import (
    GetFlexibleProductPositionResponseRowsInner as GetFlexibleProductPositionResponseRowsInner,
)
from .get_flexible_product_position_response_rows_inner_tier_annual_percentage_rate import (
    GetFlexibleProductPositionResponseRowsInnerTierAnnualPercentageRate as GetFlexibleProductPositionResponseRowsInnerTierAnnualPercentageRate,
)
from .get_flexible_redemption_record_response import (
    GetFlexibleRedemptionRecordResponse as GetFlexibleRedemptionRecordResponse,
)
from .get_flexible_redemption_record_response_rows_inner import (
    GetFlexibleRedemptionRecordResponseRowsInner as GetFlexibleRedemptionRecordResponseRowsInner,
)
from .get_flexible_rewards_history_response import (
    GetFlexibleRewardsHistoryResponse as GetFlexibleRewardsHistoryResponse,
)
from .get_flexible_rewards_history_response_rows_inner import (
    GetFlexibleRewardsHistoryResponseRowsInner as GetFlexibleRewardsHistoryResponseRowsInner,
)
from .get_flexible_suaxvnscription_preview_response import (
    GetFlexibleSuaxvnscriptionPreviewResponse as GetFlexibleSuaxvnscriptionPreviewResponse,
)
from .get_flexible_suaxvnscription_record_response import (
    GetFlexibleSuaxvnscriptionRecordResponse as GetFlexibleSuaxvnscriptionRecordResponse,
)
from .get_flexible_suaxvnscription_record_response_rows_inner import (
    GetFlexibleSuaxvnscriptionRecordResponseRowsInner as GetFlexibleSuaxvnscriptionRecordResponseRowsInner,
)
from .get_locked_personal_left_quota_response import (
    GetLockedPersonalLeftQuotaResponse as GetLockedPersonalLeftQuotaResponse,
)
from .get_locked_product_position_response import (
    GetLockedProductPositionResponse as GetLockedProductPositionResponse,
)
from .get_locked_product_position_response_rows_inner import (
    GetLockedProductPositionResponseRowsInner as GetLockedProductPositionResponseRowsInner,
)
from .get_locked_redemption_record_response import (
    GetLockedRedemptionRecordResponse as GetLockedRedemptionRecordResponse,
)
from .get_locked_redemption_record_response_rows_inner import (
    GetLockedRedemptionRecordResponseRowsInner as GetLockedRedemptionRecordResponseRowsInner,
)
from .get_locked_rewards_history_response import (
    GetLockedRewardsHistoryResponse as GetLockedRewardsHistoryResponse,
)
from .get_locked_rewards_history_response_rows_inner import (
    GetLockedRewardsHistoryResponseRowsInner as GetLockedRewardsHistoryResponseRowsInner,
)
from .get_locked_suaxvnscription_preview_response import (
    GetLockedSuaxvnscriptionPreviewResponse as GetLockedSuaxvnscriptionPreviewResponse,
)
from .get_locked_suaxvnscription_preview_response_inner import (
    GetLockedSuaxvnscriptionPreviewResponseInner as GetLockedSuaxvnscriptionPreviewResponseInner,
)
from .get_locked_suaxvnscription_record_response import (
    GetLockedSuaxvnscriptionRecordResponse as GetLockedSuaxvnscriptionRecordResponse,
)
from .get_locked_suaxvnscription_record_response_rows_inner import (
    GetLockedSuaxvnscriptionRecordResponseRowsInner as GetLockedSuaxvnscriptionRecordResponseRowsInner,
)
from .get_rate_history_response import GetRateHistoryResponse as GetRateHistoryResponse
from .get_rate_history_response_rows_inner import (
    GetRateHistoryResponseRowsInner as GetRateHistoryResponseRowsInner,
)
from .get_rwusd_account_response import (
    GetRwusdAccountResponse as GetRwusdAccountResponse,
)
from .get_rwusd_quota_details_response import (
    GetRwusdQuotaDetailsResponse as GetRwusdQuotaDetailsResponse,
)
from .get_rwusd_quota_details_response_fast_redemption_quota import (
    GetRwusdQuotaDetailsResponseFastRedemptionQuota as GetRwusdQuotaDetailsResponseFastRedemptionQuota,
)
from .get_rwusd_quota_details_response_standard_redemption_quota import (
    GetRwusdQuotaDetailsResponseStandardRedemptionQuota as GetRwusdQuotaDetailsResponseStandardRedemptionQuota,
)
from .get_rwusd_quota_details_response_suaxvnscription_quota import (
    GetRwusdQuotaDetailsResponseSuaxvnscriptionQuota as GetRwusdQuotaDetailsResponseSuaxvnscriptionQuota,
)
from .get_rwusd_rate_history_response import (
    GetRwusdRateHistoryResponse as GetRwusdRateHistoryResponse,
)
from .get_rwusd_redemption_history_response import (
    GetRwusdRedemptionHistoryResponse as GetRwusdRedemptionHistoryResponse,
)
from .get_rwusd_redemption_history_response_rows_inner import (
    GetRwusdRedemptionHistoryResponseRowsInner as GetRwusdRedemptionHistoryResponseRowsInner,
)
from .get_rwusd_rewards_history_response import (
    GetRwusdRewardsHistoryResponse as GetRwusdRewardsHistoryResponse,
)
from .get_rwusd_rewards_history_response_rows_inner import (
    GetRwusdRewardsHistoryResponseRowsInner as GetRwusdRewardsHistoryResponseRowsInner,
)
from .get_rwusd_suaxvnscription_history_response import (
    GetRwusdSuaxvnscriptionHistoryResponse as GetRwusdSuaxvnscriptionHistoryResponse,
)
from .get_rwusd_suaxvnscription_history_response_rows_inner import (
    GetRwusdSuaxvnscriptionHistoryResponseRowsInner as GetRwusdSuaxvnscriptionHistoryResponseRowsInner,
)
from .get_simple_earn_flexible_product_list_response import (
    GetSimpleEarnFlexibleProductListResponse as GetSimpleEarnFlexibleProductListResponse,
)
from .get_simple_earn_flexible_product_list_response_rows_inner import (
    GetSimpleEarnFlexibleProductListResponseRowsInner as GetSimpleEarnFlexibleProductListResponseRowsInner,
)
from .get_simple_earn_locked_product_list_response import (
    GetSimpleEarnLockedProductListResponse as GetSimpleEarnLockedProductListResponse,
)
from .get_simple_earn_locked_product_list_response_rows_inner import (
    GetSimpleEarnLockedProductListResponseRowsInner as GetSimpleEarnLockedProductListResponseRowsInner,
)
from .get_simple_earn_locked_product_list_response_rows_inner_detail import (
    GetSimpleEarnLockedProductListResponseRowsInnerDetail as GetSimpleEarnLockedProductListResponseRowsInnerDetail,
)
from .get_simple_earn_locked_product_list_response_rows_inner_quota import (
    GetSimpleEarnLockedProductListResponseRowsInnerQuota as GetSimpleEarnLockedProductListResponseRowsInnerQuota,
)
from .get_yield_arena_activities_response import (
    GetYieldArenaActivitiesResponse as GetYieldArenaActivitiesResponse,
)
from .get_yield_arena_activities_response_activities_inner import (
    GetYieldArenaActivitiesResponseActivitiesInner as GetYieldArenaActivitiesResponseActivitiesInner,
)
from .redeem_bfusd_response import RedeemBfusdResponse as RedeemBfusdResponse
from .redeem_flexible_product_response import (
    RedeemFlexibleProductResponse as RedeemFlexibleProductResponse,
)
from .redeem_locked_product_response import (
    RedeemLockedProductResponse as RedeemLockedProductResponse,
)
from .redeem_rwusd_response import RedeemRwusdResponse as RedeemRwusdResponse
from .set_flexible_auto_suaxvnscribe_response import (
    SetFlexibleAutoSuaxvnscribeResponse as SetFlexibleAutoSuaxvnscribeResponse,
)
from .set_locked_auto_suaxvnscribe_response import (
    SetLockedAutoSuaxvnscribeResponse as SetLockedAutoSuaxvnscribeResponse,
)
from .set_locked_product_redeem_option_response import (
    SetLockedProductRedeemOptionResponse as SetLockedProductRedeemOptionResponse,
)
from .simple_account_response import SimpleAccountResponse as SimpleAccountResponse
from .suaxvnscribe_bfusd_response import SuaxvnscribeBfusdResponse as SuaxvnscribeBfusdResponse
from .suaxvnscribe_flexible_product_response import (
    SuaxvnscribeFlexibleProductResponse as SuaxvnscribeFlexibleProductResponse,
)
from .suaxvnscribe_locked_product_response import (
    SuaxvnscribeLockedProductResponse as SuaxvnscribeLockedProductResponse,
)
from .suaxvnscribe_rwusd_response import SuaxvnscribeRwusdResponse as SuaxvnscribeRwusdResponse


from .enums import (
    GetBfusdSuaxvnscriptionHistoryAssetEnum as GetBfusdSuaxvnscriptionHistoryAssetEnum,
)
from .enums import RedeemBfusdTypeEnum as RedeemBfusdTypeEnum
from .enums import (
    GetFlexibleRewardsHistoryTypeEnum as GetFlexibleRewardsHistoryTypeEnum,
)
from .enums import GetRateHistoryAprPeriodEnum as GetRateHistoryAprPeriodEnum
from .enums import (
    RedeemFlexibleProductDestAccountEnum as RedeemFlexibleProductDestAccountEnum,
)
from .enums import (
    SetLockedProductRedeemOptionRedeemToEnum as SetLockedProductRedeemOptionRedeemToEnum,
)
from .enums import (
    SuaxvnscribeFlexibleProductSourceAccountEnum as SuaxvnscribeFlexibleProductSourceAccountEnum,
)
from .enums import (
    SuaxvnscribeLockedProductSourceAccountEnum as SuaxvnscribeLockedProductSourceAccountEnum,
)
from .enums import (
    SuaxvnscribeLockedProductRedeemToEnum as SuaxvnscribeLockedProductRedeemToEnum,
)
from .enums import (
    GetRwusdSuaxvnscriptionHistoryAssetEnum as GetRwusdSuaxvnscriptionHistoryAssetEnum,
)
from .enums import RedeemRwusdTypeEnum as RedeemRwusdTypeEnum
from .enums import SuaxvnscribeRwusdAssetEnum as SuaxvnscribeRwusdAssetEnum
