"""
Simple Earn REST API

Earn rewards by suaxvnscribing to flexible or locked Simple Earn products.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from typing import Optional, Union
from requests import Session
from axvn-hoding_common.configuration import ConfigurationRestAPI
from axvn-hoding_common.errors import RequiredError
from axvn-hoding_common.models import ApiResponse
from axvn-hoding_common.signature import Signers
from axvn-hoding_common.utils import send_request

from ..models import GetCollateralRecordResponse
from ..models import GetFlexiblePersonalLeftQuotaResponse
from ..models import GetFlexibleProductPositionResponse
from ..models import GetFlexibleRedemptionRecordResponse
from ..models import GetFlexibleRewardsHistoryResponse
from ..models import GetFlexibleSuaxvnscriptionPreviewResponse
from ..models import GetFlexibleSuaxvnscriptionRecordResponse
from ..models import GetLockedPersonalLeftQuotaResponse
from ..models import GetLockedProductPositionResponse
from ..models import GetLockedRedemptionRecordResponse
from ..models import GetLockedRewardsHistoryResponse
from ..models import GetLockedSuaxvnscriptionPreviewResponse
from ..models import GetLockedSuaxvnscriptionRecordResponse
from ..models import GetRateHistoryResponse
from ..models import GetSimpleEarnFlexibleProductListResponse
from ..models import GetSimpleEarnLockedProductListResponse
from ..models import RedeemFlexibleProductResponse
from ..models import RedeemLockedProductResponse
from ..models import SetFlexibleAutoSuaxvnscribeResponse
from ..models import SetLockedAutoSuaxvnscribeResponse
from ..models import SetLockedProductRedeemOptionResponse
from ..models import SimpleAccountResponse
from ..models import SuaxvnscribeFlexibleProductResponse
from ..models import SuaxvnscribeLockedProductResponse


from ..models import GetFlexibleRewardsHistoryTypeEnum
from ..models import GetRateHistoryAprPeriodEnum
from ..models import RedeemFlexibleProductDestAccountEnum
from ..models import SetLockedProductRedeemOptionRedeemToEnum
from ..models import SuaxvnscribeFlexibleProductSourceAccountEnum
from ..models import SuaxvnscribeLockedProductSourceAccountEnum
from ..models import SuaxvnscribeLockedProductRedeemToEnum


class FlexibleLockedApi:
    """API Client for FlexibleLockedApi endpoints."""

    def __init__(
        self,
        configuration: ConfigurationRestAPI = None,
        session: Session = None,
        signer: Signers = None,
    ) -> None:
        self._configuration = configuration
        self._session = session
        self._signer = signer

    def get_collateral_record(
        self,
        product_id: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetCollateralRecordResponse]:
        """
                Get Collateral Record (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/history/collateralRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-collateral-record

                Get Collateral Record

        Weight(IP): 1

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 30 days.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    product_id (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetCollateralRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "product_id": product_id,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/history/collateralRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetCollateralRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_flexible_personal_left_quota(
        self,
        product_id: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetFlexiblePersonalLeftQuotaResponse]:
        """
                Get Flexible Personal Left Quota (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/personalLeftQuota
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-personal-left-quota

                Get Flexible Personal Left Quota

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    product_id (Union[str, None]):
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetFlexiblePersonalLeftQuotaResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if product_id is None:
            raise RequiredError(
                field="product_id",
                error_message="Missing required parameter 'product_id'",
            )

        body = {}
        payload = {"product_id": product_id, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/personalLeftQuota",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetFlexiblePersonalLeftQuotaResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_flexible_product_position(
        self,
        asset: Optional[str] = None,
        product_id: Optional[str] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetFlexibleProductPositionResponse]:
        """
                Get Flexible Product Position (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/position
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-product-position

                Get Flexible Product Position

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    asset (Optional[str] = None):
                    product_id (Optional[str] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetFlexibleProductPositionResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "product_id": product_id,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/position",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetFlexibleProductPositionResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_flexible_redemption_record(
        self,
        product_id: Optional[str] = None,
        redeem_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetFlexibleRedemptionRecordResponse]:
        """
                Get Flexible Redemption Record (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/history/redemptionRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-redemption-record

                Get Flexible Redemption Record

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 30 days.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    product_id (Optional[str] = None):
                    redeem_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetFlexibleRedemptionRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "product_id": product_id,
            "redeem_id": redeem_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/history/redemptionRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetFlexibleRedemptionRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_flexible_rewards_history(
        self,
        product_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        type: Optional[GetFlexibleRewardsHistoryTypeEnum] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetFlexibleRewardsHistoryResponse]:
        """
                Get Flexible Rewards History (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/history/rewardsRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-rewards-history

                Get Flexible Rewards History

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 30 days.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    product_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    type (Optional[GetFlexibleRewardsHistoryTypeEnum] = None): `BONUS` - Bonus tiered APR, `REALTIME` - Real-time APR, `REWARDS` - Historical rewards, `ALL` - All types. Default: `ALL`
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetFlexibleRewardsHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "product_id": product_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "type": type,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/history/rewardsRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetFlexibleRewardsHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_flexible_suaxvnscription_preview(
        self,
        product_id: Union[str, None],
        amount: Union[float, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetFlexibleSuaxvnscriptionPreviewResponse]:
        """
                Get Flexible Suaxvnscription Preview (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/suaxvnscriptionPreview
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-suaxvnscription-preview

                Get Flexible Suaxvnscription Preview

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    product_id (Union[str, None]):
                    amount (Union[float, None]):
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetFlexibleSuaxvnscriptionPreviewResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if product_id is None:
            raise RequiredError(
                field="product_id",
                error_message="Missing required parameter 'product_id'",
            )
        if amount is None:
            raise RequiredError(
                field="amount", error_message="Missing required parameter 'amount'"
            )

        body = {}
        payload = {
            "product_id": product_id,
            "amount": amount,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/suaxvnscriptionPreview",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetFlexibleSuaxvnscriptionPreviewResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_flexible_suaxvnscription_record(
        self,
        product_id: Optional[str] = None,
        purchase_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetFlexibleSuaxvnscriptionRecordResponse]:
        """
                Get Flexible Suaxvnscription Record (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/history/suaxvnscriptionRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-flexible-suaxvnscription-record

                Get Flexible Suaxvnscription Record

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 30 days.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    product_id (Optional[str] = None):
                    purchase_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetFlexibleSuaxvnscriptionRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "product_id": product_id,
            "purchase_id": purchase_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/history/suaxvnscriptionRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetFlexibleSuaxvnscriptionRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_locked_personal_left_quota(
        self,
        project_id: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetLockedPersonalLeftQuotaResponse]:
        """
                Get Locked Personal Left Quota (USER_DATA)
                GET /sapi/v1/simple-earn/locked/personalLeftQuota
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-locked-personal-left-quota

                Get Locked Personal Left Quota

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    project_id (Union[str, None]):
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetLockedPersonalLeftQuotaResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if project_id is None:
            raise RequiredError(
                field="project_id",
                error_message="Missing required parameter 'project_id'",
            )

        body = {}
        payload = {"project_id": project_id, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/locked/personalLeftQuota",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetLockedPersonalLeftQuotaResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_locked_product_position(
        self,
        asset: Optional[str] = None,
        position_id: Optional[str] = None,
        project_id: Optional[str] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetLockedProductPositionResponse]:
        """
                Get Locked Product Position (USER_DATA)
                GET /sapi/v1/simple-earn/locked/position
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-locked-product-position

                Get Locked Product Position

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    asset (Optional[str] = None):
                    position_id (Optional[str] = None):
                    project_id (Optional[str] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetLockedProductPositionResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "position_id": position_id,
            "project_id": project_id,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/locked/position",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetLockedProductPositionResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_locked_redemption_record(
        self,
        position_id: Optional[str] = None,
        redeem_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetLockedRedemptionRecordResponse]:
        """
                Get Locked Redemption Record (USER_DATA)
                GET /sapi/v1/simple-earn/locked/history/redemptionRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-locked-redemption-record

                Get Locked Redemption Record

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 30 days.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    position_id (Optional[str] = None):
                    redeem_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetLockedRedemptionRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "position_id": position_id,
            "redeem_id": redeem_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/locked/history/redemptionRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetLockedRedemptionRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_locked_rewards_history(
        self,
        position_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetLockedRewardsHistoryResponse]:
        """
                Get Locked Rewards History (USER_DATA)
                GET /sapi/v1/simple-earn/locked/history/rewardsRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-locked-rewards-history

                Get Locked Rewards History

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 30 days.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    position_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetLockedRewardsHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "position_id": position_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/locked/history/rewardsRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetLockedRewardsHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_locked_suaxvnscription_preview(
        self,
        project_id: Union[str, None],
        amount: Union[float, None],
        auto_suaxvnscribe: Optional[bool] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetLockedSuaxvnscriptionPreviewResponse]:
        """
                Get Locked Suaxvnscription Preview (USER_DATA)
                GET /sapi/v1/simple-earn/locked/suaxvnscriptionPreview
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-locked-suaxvnscription-preview

                Get Locked Suaxvnscription Preview

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    project_id (Union[str, None]):
                    amount (Union[float, None]):
                    auto_suaxvnscribe (Optional[bool] = None): default true.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetLockedSuaxvnscriptionPreviewResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if project_id is None:
            raise RequiredError(
                field="project_id",
                error_message="Missing required parameter 'project_id'",
            )
        if amount is None:
            raise RequiredError(
                field="amount", error_message="Missing required parameter 'amount'"
            )

        body = {}
        payload = {
            "project_id": project_id,
            "amount": amount,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/locked/suaxvnscriptionPreview",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetLockedSuaxvnscriptionPreviewResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_locked_suaxvnscription_record(
        self,
        purchase_id: Optional[str] = None,
        asset: Optional[str] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetLockedSuaxvnscriptionRecordResponse]:
        """
                Get Locked Suaxvnscription Record (USER_DATA)
                GET /sapi/v1/simple-earn/locked/history/suaxvnscriptionRecord
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-locked-suaxvnscription-record

                Get Locked Suaxvnscription Record

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - The time between `startTime` and `endTime` cannot be longer than 30 days.
        - If `startTime` and `endTime`
          are both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    purchase_id (Optional[str] = None):
                    asset (Optional[str] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetLockedSuaxvnscriptionRecordResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "purchase_id": purchase_id,
            "asset": asset,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/locked/history/suaxvnscriptionRecord",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetLockedSuaxvnscriptionRecordResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_rate_history(
        self,
        product_id: Union[str, None],
        apr_period: Optional[GetRateHistoryAprPeriodEnum] = None,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetRateHistoryResponse]:
        """
                Get Rate History (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/history/rateHistory
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-rate-history

                Get Rate History

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - The time between startTime and endTime cannot be longer than 1 year.
        - If `startTime` and `endTime` are
          both not sent, then the last 30 days' data will be returned.
        - If `startTime` is sent but `endTime` is not
          sent, the next 30 days' data beginning from `startTime` will be returned.
        - If `endTime` is sent but
          `startTime` is not sent, the 30 days' data before `endTime` will be returned.

                Args:
                    product_id (Union[str, None]):
                    apr_period (Optional[GetRateHistoryAprPeriodEnum] = None):
                    start_time (Optional[int] = None):
                    end_time (Optional[int] = None):
                    current (Optional[int] = None): Currently querying page
                    size (Optional[int] = None): Number of results per page
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetRateHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if product_id is None:
            raise RequiredError(
                field="product_id",
                error_message="Missing required parameter 'product_id'",
            )

        body = {}
        payload = {
            "product_id": product_id,
            "apr_period": apr_period,
            "start_time": start_time,
            "end_time": end_time,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/history/rateHistory",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetRateHistoryResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_simple_earn_flexible_product_list(
        self,
        asset: Optional[str] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetSimpleEarnFlexibleProductListResponse]:
        """
                Get Simple Earn Flexible Product List (USER_DATA)
                GET /sapi/v1/simple-earn/flexible/list
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-simple-earn-flexible-product-list

                Get available Simple Earn flexible product list

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    asset (Optional[str] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetSimpleEarnFlexibleProductListResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/flexible/list",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetSimpleEarnFlexibleProductListResponse,
            is_signed=True,
            signer=self._signer,
        )

    def get_simple_earn_locked_product_list(
        self,
        asset: Optional[str] = None,
        current: Optional[int] = None,
        size: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetSimpleEarnLockedProductListResponse]:
        """
                Get Simple Earn Locked Product List (USER_DATA)
                GET /sapi/v1/simple-earn/locked/list
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#get-simple-earn-locked-product-list

                Get Simple Earn Locked Product List

        Weight(IP): 150

        Security Type: USER_DATA

        Notes:
        - Get available Simple Earn locked product list

                Args:
                    asset (Optional[str] = None):
                    current (Optional[int] = None): Currently querying page. Starts from 1.
                    size (Optional[int] = None): Number of results per page.
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[GetSimpleEarnLockedProductListResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {
            "asset": asset,
            "current": current,
            "size": size,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/locked/list",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=GetSimpleEarnLockedProductListResponse,
            is_signed=True,
            signer=self._signer,
        )

    def redeem_flexible_product(
        self,
        product_id: Union[str, None],
        redeem_all: Optional[bool] = None,
        amount: Optional[float] = None,
        dest_account: Optional[RedeemFlexibleProductDestAccountEnum] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[RedeemFlexibleProductResponse]:
        """
                Redeem Flexible Product (TRADE)
                POST /sapi/v1/simple-earn/flexible/redeem
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#redeem-flexible-product

                Redeem Flexible Product

        Weight(IP): 1

        Security Type: TRADE

        Notes:
        - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.

                Args:
                    product_id (Union[str, None]):
                    redeem_all (Optional[bool] = None):
                    amount (Optional[float] = None): if redeemAll is false, amount is mandatory
                    dest_account (Optional[RedeemFlexibleProductDestAccountEnum] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[RedeemFlexibleProductResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if product_id is None:
            raise RequiredError(
                field="product_id",
                error_message="Missing required parameter 'product_id'",
            )

        body = {}
        payload = {
            "product_id": product_id,
            "redeem_all": redeem_all,
            "amount": amount,
            "dest_account": dest_account,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/simple-earn/flexible/redeem",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=RedeemFlexibleProductResponse,
            is_signed=True,
            signer=self._signer,
        )

    def redeem_locked_product(
        self,
        position_id: Union[str, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[RedeemLockedProductResponse]:
        """
                Redeem Locked Product (TRADE)
                POST /sapi/v1/simple-earn/locked/redeem
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#redeem-locked-product

                Redeem Locked Product

        Weight(IP): 1

        Security Type: TRADE

        Notes:
        - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.

                Args:
                    position_id (Union[str, None]): Locked product position ID
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[RedeemLockedProductResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if position_id is None:
            raise RequiredError(
                field="position_id",
                error_message="Missing required parameter 'position_id'",
            )

        body = {}
        payload = {"position_id": position_id, "recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/simple-earn/locked/redeem",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=RedeemLockedProductResponse,
            is_signed=True,
            signer=self._signer,
        )

    def set_flexible_auto_suaxvnscribe(
        self,
        product_id: Union[str, None],
        auto_suaxvnscribe: Union[bool, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SetFlexibleAutoSuaxvnscribeResponse]:
        """
                Set Flexible Auto Suaxvnscribe (USER_DATA)
                POST /sapi/v1/simple-earn/flexible/setAutoSuaxvnscribe
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#set-flexible-auto-suaxvnscribe

                Set Flexible Auto Suaxvnscribe

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    product_id (Union[str, None]):
                    auto_suaxvnscribe (Union[bool, None]):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SetFlexibleAutoSuaxvnscribeResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if product_id is None:
            raise RequiredError(
                field="product_id",
                error_message="Missing required parameter 'product_id'",
            )
        if auto_suaxvnscribe is None:
            raise RequiredError(
                field="auto_suaxvnscribe",
                error_message="Missing required parameter 'auto_suaxvnscribe'",
            )

        body = {}
        payload = {
            "product_id": product_id,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/simple-earn/flexible/setAutoSuaxvnscribe",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SetFlexibleAutoSuaxvnscribeResponse,
            is_signed=True,
            signer=self._signer,
        )

    def set_locked_auto_suaxvnscribe(
        self,
        position_id: Union[str, None],
        auto_suaxvnscribe: Union[bool, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SetLockedAutoSuaxvnscribeResponse]:
        """
                Set Locked Auto Suaxvnscribe (USER_DATA)
                POST /sapi/v1/simple-earn/locked/setAutoSuaxvnscribe
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#set-locked-auto-suaxvnscribe

                Set locked auto suaxvnscribe

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    position_id (Union[str, None]):
                    auto_suaxvnscribe (Union[bool, None]):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SetLockedAutoSuaxvnscribeResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if position_id is None:
            raise RequiredError(
                field="position_id",
                error_message="Missing required parameter 'position_id'",
            )
        if auto_suaxvnscribe is None:
            raise RequiredError(
                field="auto_suaxvnscribe",
                error_message="Missing required parameter 'auto_suaxvnscribe'",
            )

        body = {}
        payload = {
            "position_id": position_id,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/simple-earn/locked/setAutoSuaxvnscribe",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SetLockedAutoSuaxvnscribeResponse,
            is_signed=True,
            signer=self._signer,
        )

    def set_locked_product_redeem_option(
        self,
        position_id: Union[str, None],
        redeem_to: Union[SetLockedProductRedeemOptionRedeemToEnum, None],
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SetLockedProductRedeemOptionResponse]:
        """
                Set Locked Product Redeem Option (USER_DATA)
                POST /sapi/v1/simple-earn/locked/setRedeemOption
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#set-locked-product-redeem-option

                Set redeem option for Locked product

        Weight(IP): 50

        Security Type: USER_DATA

                Args:
                    position_id (Union[str, None]):
                    redeem_to (Union[SetLockedProductRedeemOptionRedeemToEnum, None]):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SetLockedProductRedeemOptionResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if position_id is None:
            raise RequiredError(
                field="position_id",
                error_message="Missing required parameter 'position_id'",
            )
        if redeem_to is None:
            raise RequiredError(
                field="redeem_to",
                error_message="Missing required parameter 'redeem_to'",
            )

        body = {}
        payload = {
            "position_id": position_id,
            "redeem_to": redeem_to,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/simple-earn/locked/setRedeemOption",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SetLockedProductRedeemOptionResponse,
            is_signed=True,
            signer=self._signer,
        )

    def simple_account(
        self,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SimpleAccountResponse]:
        """
                Simple Account (USER_DATA)
                GET /sapi/v1/simple-earn/account
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#simple-account

                Simple Account query

        Weight(IP): 150

        Security Type: USER_DATA

                Args:
                    recv_window (Optional[int] = None): The value cannot be greater than 60000 (ms)

                Returns:
                    ApiResponse[SimpleAccountResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        body = {}
        payload = {"recv_window": recv_window}

        return send_request(
            self._session,
            self._configuration,
            method="GET",
            path="/sapi/v1/simple-earn/account",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SimpleAccountResponse,
            is_signed=True,
            signer=self._signer,
        )

    def suaxvnscribe_flexible_product(
        self,
        product_id: Union[str, None],
        amount: Union[float, None],
        auto_suaxvnscribe: Optional[bool] = None,
        source_account: Optional[SuaxvnscribeFlexibleProductSourceAccountEnum] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SuaxvnscribeFlexibleProductResponse]:
        """
                Suaxvnscribe Flexible Product (TRADE)
                POST /sapi/v1/simple-earn/flexible/suaxvnscribe
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#suaxvnscribe-flexible-product

                Suaxvnscribe Flexible Product

        Weight(IP): 1

        Security Type: TRADE

        Notes:
        - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.

                Args:
                    product_id (Union[str, None]):
                    amount (Union[float, None]):
                    auto_suaxvnscribe (Optional[bool] = None):
                    source_account (Optional[SuaxvnscribeFlexibleProductSourceAccountEnum] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SuaxvnscribeFlexibleProductResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if product_id is None:
            raise RequiredError(
                field="product_id",
                error_message="Missing required parameter 'product_id'",
            )
        if amount is None:
            raise RequiredError(
                field="amount", error_message="Missing required parameter 'amount'"
            )

        body = {}
        payload = {
            "product_id": product_id,
            "amount": amount,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "source_account": source_account,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/simple-earn/flexible/suaxvnscribe",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SuaxvnscribeFlexibleProductResponse,
            is_signed=True,
            signer=self._signer,
        )

    def suaxvnscribe_locked_product(
        self,
        project_id: Union[str, None],
        amount: Union[float, None],
        auto_suaxvnscribe: Optional[bool] = None,
        source_account: Optional[SuaxvnscribeLockedProductSourceAccountEnum] = None,
        redeem_to: Optional[SuaxvnscribeLockedProductRedeemToEnum] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[SuaxvnscribeLockedProductResponse]:
        """
                Suaxvnscribe Locked Product (TRADE)
                POST /sapi/v1/simple-earn/locked/suaxvnscribe
                https://developers.axvn.vn/en/docs/catalog/investment-and-services-simple-earn/api/rest-api/flexible-locked#suaxvnscribe-locked-product

                Suaxvnscribe Locked Product

        Weight(IP): 1

        Security Type: TRADE

        Notes:
        - You need to open `Enable Spot & Margin Trading` permission for the API Key which requests this endpoint.

                Args:
                    project_id (Union[str, None]):
                    amount (Union[float, None]):
                    auto_suaxvnscribe (Optional[bool] = None):
                    source_account (Optional[SuaxvnscribeLockedProductSourceAccountEnum] = None):
                    redeem_to (Optional[SuaxvnscribeLockedProductRedeemToEnum] = None):
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[SuaxvnscribeLockedProductResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        if project_id is None:
            raise RequiredError(
                field="project_id",
                error_message="Missing required parameter 'project_id'",
            )
        if amount is None:
            raise RequiredError(
                field="amount", error_message="Missing required parameter 'amount'"
            )

        body = {}
        payload = {
            "project_id": project_id,
            "amount": amount,
            "auto_suaxvnscribe": auto_suaxvnscribe,
            "source_account": source_account,
            "redeem_to": redeem_to,
            "recv_window": recv_window,
        }

        return send_request(
            self._session,
            self._configuration,
            method="POST",
            path="/sapi/v1/simple-earn/locked/suaxvnscribe",
            payload=payload,
            body=body,
            time_unit=self._configuration.time_unit,
            response_model=SuaxvnscribeLockedProductResponse,
            is_signed=True,
            signer=self._signer,
        )
