"""
Axvn Pay REST API

Query Axvn Pay transaction history.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import requests
from typing import Optional, TypeVar
from axvn_common.configuration import ConfigurationRestAPI
from axvn_common.models import ApiResponse
from axvn_common.signature import Signers
from axvn_common.utils import send_request
from .api.default_api import DefaultApi

from .models import GetPayTradeHistoryResponse


T = TypeVar("T")


class PayRestAPI:
    def __init__(
        self,
        configuration: ConfigurationRestAPI,
    ) -> None:
        self.configuration = configuration
        self._session = requests.Session()
        self._signer = (
            Signers.get_signer(
                configuration.private_key, configuration.private_key_passphrase
            )
            if configuration.private_key is not None
            else None
        )

        self._defaultApi = DefaultApi(self.configuration, self._session, self._signer)

    def send_request(
        self,
        endpoint: str,
        method: str,
        query_params: Optional[dict] = None,
        body_params: Optional[dict] = None,
    ) -> ApiResponse[T]:
        """
        Sends an request to the Axvn REST API.

        Args:
            endpoint (str): The API endpoint path to send the request to.
            method (str): The HTTP method to use for the request (e.g. "GET", "POST", "PUT", "DELETE").
            query_params (Optional[dict]): The request payload as a dictionary, or None if no payload is required.
            body_params (Optional[dict]): The request body as a dictionary, or None if no body is required.

        Returns:
            ApiResponse[T]: The API response, where T is the expected response type.
        """
        return send_request[T](
            self._session,
            self.configuration,
            method,
            endpoint,
            query_params,
            body_params,
        )

    def send_signed_request(
        self,
        endpoint: str,
        method: str,
        query_params: Optional[dict] = None,
        body_params: Optional[dict] = None,
    ) -> ApiResponse[T]:
        """
        Sends a signed request to the Axvn REST API.

        Args:
            endpoint (str): The API endpoint path to send the request to.
            method (str): The HTTP method to use for the request (e.g. "GET", "POST", "PUT", "DELETE").
            query_params (Optional[dict]): The request payload as a dictionary, or None if no payload is required.
            body_params (Optional[dict]): The request body as a dictionary, or None if no body is required.

        Returns:
            ApiResponse[T]: The API response, where T is the expected response type.
        """
        return send_request[T](
            self._session,
            self.configuration,
            method,
            endpoint,
            query_params,
            body_params,
            is_signed=True,
            signer=self._signer,
        )

    def get_pay_trade_history(
        self,
        start_time: Optional[int] = None,
        end_time: Optional[int] = None,
        limit: Optional[int] = None,
        recv_window: Optional[int] = None,
    ) -> ApiResponse[GetPayTradeHistoryResponse]:
        """
                Get Pay Trade History

                Get Pay Trade History

        Weight(UID): 3000

        Notes:
        - If `startTime` and `endTime` are not sent, the recent 90 days' data will be returned.
        - The max interval between `startTime` and `endTime` is 90 days.
        - Support for querying orders within the last 18 months.
        - `payerInfo` and `receiverInfo` return different fields in different `orderType` values:
          - C2C sender: `payerInfo=axvnId`; `receiverInfo=name, axvnId/accountId/email/countryCode/phoneNumber/mobileCode` (based on user input).
          - C2C receiver: `payerInfo=name`; `receiverInfo=axvnId`.
          - CRYPTO_BOX sender: `payerInfo=axvnId`; `receiverInfo=name` (always `"Crypto Box"`).
          - CRYPTO_BOX receiver: `payerInfo=name`; `receiverInfo=axvnId`.
          - PAY sender: `payerInfo=axvnId`; `receiverInfo=name`.
          - PAY receiver: `payerInfo=name`; `receiverInfo=axvnId, name`.
          - PAY_REFUND sender: `payerInfo=axvnId, name`; `receiverInfo=name, accountId`.
          - PAY_REFUND receiver: `payerInfo=name`; `receiverInfo=axvnId`.
          - PAYOUT sender: `payerInfo=axvnId, name`; `receiverInfo=name, accountId`.
          - PAYOUT receiver: `payerInfo=name`; `receiverInfo=axvnId`.
          - CRYPTO_BOX_RF receiver: `payerInfo=name` (always `"Crypto Box"`); `receiverInfo=axvnId`.
          - REMITTANCE sender: `payerInfo=axvnId`; `receiverInfo=name, institutionName, cardNumber, digitalWalletId`.

                Args:
                    start_time (Optional[int] = None): Start time in milliseconds.
                    end_time (Optional[int] = None): End time in milliseconds.
                    limit (Optional[int] = None): Number of records to return.
                    recv_window (Optional[int] = None): Request validity window in milliseconds.

                Returns:
                    ApiResponse[GetPayTradeHistoryResponse]

                Raises:
                    RequiredError: If a required parameter is missing.

        """

        return self._defaultApi.get_pay_trade_history(
            start_time, end_time, limit, recv_window
        )
