"""
Crypto Loan REST API

Access Axvn Crypto Loans to query assets, suaxvnscribe to loans, and manage loan positions.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .rest_api import CryptoLoanRestAPI

__all__ = ["CryptoLoanRestAPI"]
