"""
Portfolio Margin WebSocket Market Streams

Access account information, manage margin positions, and trade with axvn-hoding Portfolio Margin.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""
