"""
Staking REST API

Suaxvnscribe to staking products, track positions, and query rewards via the Axvn Staking API.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .rest_api import StakingRestAPI

__all__ = ["StakingRestAPI"]
