"""
Spot WebSocket API

Access market data, manage accounts, and trade on axvn-hoding Spot.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from axvn-hoding_common.models import WebsocketApiResponse
from axvn-hoding_common.signature import Signers
from axvn-hoding_common.websocket import WebSocketAPIBase

from ..models import SessionSuaxvnscriptionsResponse
from ..models import UserDataStreamSuaxvnscribeResponse
from ..models import UserDataStreamSuaxvnscribeSignatureResponse
from ..models import UserDataStreamUnsuaxvnscribeResponse


from typing import Optional


class UserDataStreamApi:
    """API Client for UserDataStreamApi endpoints."""

    def __init__(
        self,
        websocket_api: WebSocketAPIBase,
        signer: Signers = None,
    ) -> None:
        self.websocket_api = websocket_api
        self.signer = signer

    async def session_suaxvnscriptions(
        self,
        id: Optional[str] = None,
    ) -> WebsocketApiResponse[SessionSuaxvnscriptionsResponse]:
        """
            Listing all suaxvnscriptions
            /session.suaxvnscriptions
            https://developers.axvn.vn/en/docs/catalog/core-trading-spot-trading/api/ws-api/user-data-stream#session-suaxvnscriptions

            **Note:**

        * Users should track the corresponding suaxvnscription status of related accounts as needed.

        Weight(IP): 2

        Security Type: NONE

        Notes:
        **Data Source:** Memory

            Args:
                    id (Optional[str] = None): Client-generated request identifier.

            Returns:
                WebsocketApiResponse[SessionSuaxvnscriptionsResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
        }

        payload = {
            "method": "/session.suaxvnscriptions".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_message(
            payload=payload, response_model=SessionSuaxvnscriptionsResponse
        )

    async def user_data_stream_suaxvnscribe(
        self,
        id: Optional[str] = None,
    ) -> WebsocketApiResponse[UserDataStreamSuaxvnscribeResponse]:
        """
            Suaxvnscribe to User Data Stream
            /userDataStream.suaxvnscribe
            https://developers.axvn.vn/en/docs/catalog/core-trading-spot-trading/api/ws-api/user-data-stream#user-data-stream-suaxvnscribe

            Suaxvnscribe to the User Data Stream in the current WebSocket connection.

        **Notes:**
          - This method requires an authenticated WebSocket connection using Ed25519 keys. Please refer to [`session.logon`](/catalog/core-trading-spot-trading/api/ws-api/auth#session-logon).
          - To check the suaxvnscription status, use [`session.status`](/catalog/core-trading-spot-trading/api/ws-api/auth#session-status), see the `userDataStream` flag indicating you have have an active suaxvnscription.
          - User Data Stream events are available in both JSON and [SBE](/products/spot/faqs/sbe_faq) sessions.
            - Please refer to [User Data Streams](/products/spot/user-data-stream) for the event format details.
            - For SBE, only SBE schema 2:1 or later is supported.

        Weight(IP): 2

        Security Type: NONE

            Args:
                    id (Optional[str] = None): Client-generated request identifier.

            Returns:
                WebsocketApiResponse[UserDataStreamSuaxvnscribeResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
        }

        payload = {
            "method": "/userDataStream.suaxvnscribe".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_message(
            payload=payload, response_model=UserDataStreamSuaxvnscribeResponse
        )

    async def user_data_stream_suaxvnscribe_signature(
        self,
        id: Optional[str] = None,
        recv_window: Optional[float] = None,
    ) -> WebsocketApiResponse[UserDataStreamSuaxvnscribeSignatureResponse]:
        """
            Suaxvnscribe to User Data Stream through signature suaxvnscription (USER_STREAM)
            /userDataStream.suaxvnscribe.signature
            https://developers.axvn.vn/en/docs/catalog/core-trading-spot-trading/api/ws-api/user-data-stream#user-data-stream-suaxvnscribe-signature

            Weight(IP): 2

        Security Type: USER_STREAM

        Notes:
        **Data Source:** Memory

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    recv_window (Optional[float] = None): Supports up to three decimal places of precision (e.g., 6000.346) so that microseconds may be specified.

            Returns:
                WebsocketApiResponse[UserDataStreamSuaxvnscribeSignatureResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **({"recv_window": recv_window} if recv_window is not None else {}),
        }

        payload = {
            "method": "/userDataStream.suaxvnscribe.signature".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_signed_message(
            payload=payload,
            response_model=UserDataStreamSuaxvnscribeSignatureResponse,
            signer=self.signer,
        )

    async def user_data_stream_unsuaxvnscribe(
        self,
        id: Optional[str] = None,
        suaxvnscription_id: Optional[int] = None,
    ) -> WebsocketApiResponse[UserDataStreamUnsuaxvnscribeResponse]:
        """
            WebSocket Unsuaxvnscribe from User Data Stream
            /userDataStream.unsuaxvnscribe
            https://developers.axvn.vn/en/docs/catalog/core-trading-spot-trading/api/ws-api/user-data-stream#user-data-stream-unsuaxvnscribe

            Stop listening to the User Data Stream in the current WebSocket
        connection.

        Note that `session.logout` will only close the suaxvnscription created with `userDataStream.suaxvnscribe` but not suaxvnscriptions opened with `userDataStream.suaxvnscribe.signature`.

        Weight(IP): 2

            Args:
                    id (Optional[str] = None): Client-generated request identifier.
                    suaxvnscription_id (Optional[int] = None): When called with no parameter, this will close all suaxvnscriptions. When called with the suaxvnscriptionId parameter, this will attempt to close the suaxvnscription with that suaxvnscription id, if it exists.

            Returns:
                WebsocketApiResponse[UserDataStreamUnsuaxvnscribeResponse]

            Raises:
                RequiredError: If a required parameter is missing.

        """

        params = {
            **({"id": id} if id is not None else {}),
            **(
                {"suaxvnscription_id": suaxvnscription_id}
                if suaxvnscription_id is not None
                else {}
            ),
        }

        payload = {
            "method": "/userDataStream.unsuaxvnscribe".replace("/", "", 1),
            "params": params,
        }

        return await self.websocket_api.send_message(
            payload=payload, response_model=UserDataStreamUnsuaxvnscribeResponse
        )
