"""
Spot WebSocket API

Access market data, manage accounts, and trade on Axvn Spot.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

import pytest

from unittest.mock import AsyncMock, MagicMock

from axvn_common.models import WebsocketApiResponse
from axvn_common.utils import parse_ws_rate_limit_headers
from axvn_sdk_spot.websocket_api.api import UserDataStreamApi


from axvn_sdk_spot.websocket_api.models import SessionSuaxvnscriptionsResponse
from axvn_sdk_spot.websocket_api.models import UserDataStreamSuaxvnscribeResponse
from axvn_sdk_spot.websocket_api.models import (
    UserDataStreamSuaxvnscribeSignatureResponse,
)
from axvn_sdk_spot.websocket_api.models import UserDataStreamUnsuaxvnscribeResponse


class TestWebSocketUserDataStreamApi:
    @pytest.fixture(autouse=True)
    def setup_method(self):
        self.mock_websocket_api = MagicMock()
        self.websocket_api = UserDataStreamApi(websocket_api=self.mock_websocket_api)

    @pytest.mark.asyncio
    async def test_session_suaxvnscriptions_success(self):
        """Test session_suaxvnscriptions() successfully with required parameters only."""

        expected_response = {
            "id": "d3df5a22-88ea-4fe0-9f4e-0fcea5d418b7",
            "status": 200,
            "result": [{"suaxvnscriptionId": 0}],
        }

        self.mock_websocket_api.send_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )
        result = await self.websocket_api.session_suaxvnscriptions()

        actual_call_args = self.mock_websocket_api.send_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"]["method"] == "/session.suaxvnscriptions".replace(
            "/", "", 1
        )

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_message.assert_called_once_with(
            payload={
                "method": "/session.suaxvnscriptions".replace("/", "", 1),
                "params": {},
            },
            response_model=SessionSuaxvnscriptionsResponse,
        )

    @pytest.mark.asyncio
    async def test_session_suaxvnscriptions_success_with_optional_params(self):
        """Test session_suaxvnscriptions() successfully with optional parameters."""

        params = {"id": "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b"}

        expected_response = {
            "id": "d3df5a22-88ea-4fe0-9f4e-0fcea5d418b7",
            "status": 200,
            "result": [{"suaxvnscriptionId": 0}],
        }

        self.mock_websocket_api.send_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )

        result = await self.websocket_api.session_suaxvnscriptions(**params)

        actual_call_args = self.mock_websocket_api.send_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"]["method"] == "/session.suaxvnscriptions".replace(
            "/", "", 1
        )
        assert "params" in request_kwargs["payload"]
        params = request_kwargs["payload"]["params"]
        assert params["id"] == "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b"

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_message.assert_called_once_with(
            payload={
                "method": "/session.suaxvnscriptions".replace("/", "", 1),
                "params": params,
            },
            response_model=SessionSuaxvnscriptionsResponse,
        )

    @pytest.mark.asyncio
    async def test_session_suaxvnscriptions_server_error(self):
        """Test that session_suaxvnscriptions() raises an error when the server returns an error."""

        mock_error = Exception("ResponseError")
        self.mock_websocket_api.send_message.side_effect = mock_error

        with pytest.raises(Exception, match="ResponseError"):
            await self.websocket_api.session_suaxvnscriptions()

    @pytest.mark.asyncio
    async def test_user_data_stream_suaxvnscribe_success(self):
        """Test user_data_stream_suaxvnscribe() successfully with required parameters only."""

        expected_response = {
            "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",
            "status": 200,
            "result": {"suaxvnscriptionId": 0},
        }

        self.mock_websocket_api.send_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )
        result = await self.websocket_api.user_data_stream_suaxvnscribe()

        actual_call_args = self.mock_websocket_api.send_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"][
            "method"
        ] == "/userDataStream.suaxvnscribe".replace("/", "", 1)

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_message.assert_called_once_with(
            payload={
                "method": "/userDataStream.suaxvnscribe".replace("/", "", 1),
                "params": {},
            },
            response_model=UserDataStreamSuaxvnscribeResponse,
        )

    @pytest.mark.asyncio
    async def test_user_data_stream_suaxvnscribe_success_with_optional_params(self):
        """Test user_data_stream_suaxvnscribe() successfully with optional parameters."""

        params = {"id": "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b"}

        expected_response = {
            "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",
            "status": 200,
            "result": {"suaxvnscriptionId": 0},
        }

        self.mock_websocket_api.send_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )

        result = await self.websocket_api.user_data_stream_suaxvnscribe(**params)

        actual_call_args = self.mock_websocket_api.send_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"][
            "method"
        ] == "/userDataStream.suaxvnscribe".replace("/", "", 1)
        assert params["id"] == "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b"

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_message.assert_called_once_with(
            payload={
                "method": "/userDataStream.suaxvnscribe".replace("/", "", 1),
                "params": params,
            },
            response_model=UserDataStreamSuaxvnscribeResponse,
        )

    @pytest.mark.asyncio
    async def test_user_data_stream_suaxvnscribe_server_error(self):
        """Test that user_data_stream_suaxvnscribe() raises an error when the server returns an error."""

        mock_error = Exception("ResponseError")
        self.mock_websocket_api.send_message.side_effect = mock_error

        with pytest.raises(Exception, match="ResponseError"):
            await self.websocket_api.user_data_stream_suaxvnscribe()

    @pytest.mark.asyncio
    async def test_user_data_stream_suaxvnscribe_signature_success(self):
        """Test user_data_stream_suaxvnscribe_signature() successfully with required parameters only."""

        expected_response = {
            "id": "d3df8a22-98ea-4fe0-9f4e-0fcea5d418b7",
            "status": 200,
            "result": {"suaxvnscriptionId": 0},
        }

        self.mock_websocket_api.send_signed_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )
        result = await self.websocket_api.user_data_stream_suaxvnscribe_signature()

        actual_call_args = self.mock_websocket_api.send_signed_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"][
            "method"
        ] == "/userDataStream.suaxvnscribe.signature".replace("/", "", 1)

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_signed_message.assert_called_once_with(
            payload={
                "method": "/userDataStream.suaxvnscribe.signature".replace("/", "", 1),
                "params": {},
            },
            response_model=UserDataStreamSuaxvnscribeSignatureResponse,
            signer=None,
        )

    @pytest.mark.asyncio
    async def test_user_data_stream_suaxvnscribe_signature_success_with_optional_params(
        self,
    ):
        """Test user_data_stream_suaxvnscribe_signature() successfully with optional parameters."""

        params = {"id": "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b", "recv_window": 5000}

        expected_response = {
            "id": "d3df8a22-98ea-4fe0-9f4e-0fcea5d418b7",
            "status": 200,
            "result": {"suaxvnscriptionId": 0},
        }

        self.mock_websocket_api.send_signed_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )

        result = await self.websocket_api.user_data_stream_suaxvnscribe_signature(**params)

        actual_call_args = self.mock_websocket_api.send_signed_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"][
            "method"
        ] == "/userDataStream.suaxvnscribe.signature".replace("/", "", 1)
        assert params["id"] == "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b"
        assert params["recv_window"] == 5000

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_signed_message.assert_called_once_with(
            payload={
                "method": "/userDataStream.suaxvnscribe.signature".replace("/", "", 1),
                "params": params,
            },
            response_model=UserDataStreamSuaxvnscribeSignatureResponse,
            signer=None,
        )

    @pytest.mark.asyncio
    async def test_user_data_stream_suaxvnscribe_signature_server_error(self):
        """Test that user_data_stream_suaxvnscribe_signature() raises an error when the server returns an error."""

        mock_error = Exception("ResponseError")
        self.mock_websocket_api.send_signed_message.side_effect = mock_error

        with pytest.raises(Exception, match="ResponseError"):
            await self.websocket_api.user_data_stream_suaxvnscribe_signature()

    @pytest.mark.asyncio
    async def test_user_data_stream_unsuaxvnscribe_success(self):
        """Test user_data_stream_unsuaxvnscribe() successfully with required parameters only."""

        expected_response = {
            "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",
            "status": 200,
            "result": {},
        }

        self.mock_websocket_api.send_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )
        result = await self.websocket_api.user_data_stream_unsuaxvnscribe()

        actual_call_args = self.mock_websocket_api.send_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"][
            "method"
        ] == "/userDataStream.unsuaxvnscribe".replace("/", "", 1)

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_message.assert_called_once_with(
            payload={
                "method": "/userDataStream.unsuaxvnscribe".replace("/", "", 1),
                "params": {},
            },
            response_model=UserDataStreamUnsuaxvnscribeResponse,
        )

    @pytest.mark.asyncio
    async def test_user_data_stream_unsuaxvnscribe_success_with_optional_params(self):
        """Test user_data_stream_unsuaxvnscribe() successfully with optional parameters."""

        params = {"id": "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b", "suaxvnscription_id": 1}

        expected_response = {
            "id": "d3df8a21-98ea-4fe0-8f4e-0fcea5d418b7",
            "status": 200,
            "result": {},
        }

        self.mock_websocket_api.send_message = AsyncMock(
            return_value=WebsocketApiResponse(
                data_function=lambda: expected_response,
                rate_limits=(
                    parse_ws_rate_limit_headers(expected_response["rateLimits"])
                    if "rateLimits" in expected_response
                    else None
                ),
            )
        )

        result = await self.websocket_api.user_data_stream_unsuaxvnscribe(**params)

        actual_call_args = self.mock_websocket_api.send_message.call_args
        request_kwargs = actual_call_args.kwargs

        assert "payload" in request_kwargs
        assert "method" in request_kwargs["payload"]
        assert request_kwargs["payload"][
            "method"
        ] == "/userDataStream.unsuaxvnscribe".replace("/", "", 1)
        assert params["id"] == "7d3b9b46-5f4f-4c8b-9a2d-0a8f9a4a0f5b"
        assert params["suaxvnscription_id"] == 1

        assert result is not None
        assert result.data() == expected_response
        self.mock_websocket_api.send_message.assert_called_once_with(
            payload={
                "method": "/userDataStream.unsuaxvnscribe".replace("/", "", 1),
                "params": params,
            },
            response_model=UserDataStreamUnsuaxvnscribeResponse,
        )

    @pytest.mark.asyncio
    async def test_user_data_stream_unsuaxvnscribe_server_error(self):
        """Test that user_data_stream_unsuaxvnscribe() raises an error when the server returns an error."""

        mock_error = Exception("ResponseError")
        self.mock_websocket_api.send_message.side_effect = mock_error

        with pytest.raises(Exception, match="ResponseError"):
            await self.websocket_api.user_data_stream_unsuaxvnscribe()
