"""
Crypto Loan REST API

Access axvn-hoding Crypto Loans to query assets, suaxvnscribe to loans, and manage loan positions.
The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from .flexible_rate_api import FlexibleRateApi as FlexibleRateApi
from .stable_rate_api import StableRateApi as StableRateApi
